
[functions.generate-workout-plan]
enabled = false
verify_jwt = false

[functions.generate-daily-workout]
enabled = false
verify_jwt = false
import_map = "./functions/generate-daily-workout/deno.json"
entrypoint = "./functions/generate-daily-workout/index.ts"

[functions.chat-coach]
enabled = false
verify_jwt = false

[functions.chat-onboarding]
enabled = false
verify_jwt = false

[functions.tester-list-users]
enabled = true
verify_jwt = false

[functions.tester-user-data]
enabled = true
verify_jwt = false

[functions.agent-orchestrator]
enabled = true
verify_jwt = false

[functions.agent-memory]
enabled = true
verify_jwt = false

[functions.agent-onboarding]
enabled = true
verify_jwt = false

[functions.agent-plan]
enabled = true
verify_jwt = false

[functions.agent-daily]
enabled = true
verify_jwt = false

[functions.agent-companion]
enabled = true
verify_jwt = false
