-- Initial SparkFit Database Schema for MVP

-- Enable Row Level Security (RLS)
-- (We will set up permissive policies for MVP speed, and lock down later)

-- 1. Profiles Table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  goal TEXT,
  fitness_level TEXT,
  workout_days_per_week INT,
  equipment TEXT,
  updated_at TIMESTAMP WITH TIME ZONE,
  ai_context_summary TEXT -- Generated by AI onboarding
);

-- Enable RLS on profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

-- 2. Workout Plans Table (Stores the high level plan)
CREATE TABLE workout_plans (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  plan_data JSONB NOT NULL, -- Storing the exact structured output from Gemini directly
  status TEXT DEFAULT 'active'
);

ALTER TABLE workout_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can select their own plans." ON workout_plans FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own plans." ON workout_plans FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own plans." ON workout_plans FOR UPDATE USING (auth.uid() = user_id);

-- 3. Workout Logs Table (Daily tracking)
CREATE TABLE workout_logs (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) NOT NULL,
  plan_id UUID REFERENCES workout_plans(id) NOT NULL,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  logged_data JSONB NOT NULL -- Stores { "exercise1": {"sets": 3, "reps": [10, 10, 8]}, ...}
);

ALTER TABLE workout_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own logs." ON workout_logs FOR ALL USING (auth.uid() = user_id);

-- 4. Workout Feedback Table (For AI adjustment)
CREATE TABLE workout_feedback (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) NOT NULL,
  log_id UUID REFERENCES workout_logs(id) NOT NULL,
  perceived_exertion INT, -- 1-10
  text_feedback TEXT,
  ai_adjusted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE workout_feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own feedback." ON workout_feedback FOR ALL USING (auth.uid() = user_id);

-- Helper function to automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id)
  VALUES (new.id);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the helper function after user creation
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
